# Generated by Django 6.0.4 on 2026-06-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp', 'id']},
        ),
    ]
