# Generated by Django 6.0.4 on 2026-05-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="projects",
            new_name="project",
        ),
    ]
